os: linux
dist: bionic
language: minimal

services:
  - docker

install:
  - docker build --tag test/php74xc .

script:
  - docker run --rm test/php74xc php -v | grep 7.4
  - docker run --rm test/php74xc php -m | grep xdebug
  - docker run --rm test/php74xc /usr/bin/composer -V | grep Composer

after_success:
  - docker rmi test/php74xc