os: linux
dist: bionic
language: shell

services:
  - docker

env:
  DOCKER_USERNAME: sineverba
  DOCKER_IMAGE: php74xc

install:
  - docker build --tag $DOCKER_USERNAME/$DOCKER_IMAGE .

script:
  - docker run --rm $DOCKER_USERNAME/$DOCKER_IMAGE php -v | grep 7.4
  - docker run --rm $DOCKER_USERNAME/$DOCKER_IMAGE php -m | grep xdebug
  - docker run --rm $DOCKER_USERNAME/$DOCKER_IMAGE /usr/bin/composer -V | grep Composer

after_success:
  - chmod +x ./deploy.sh
  - ./deploy.sh

deploy:
  provider: script
  script: ./deploy.sh
  on:
    tags: true