os: linux
dist: bionic
language: shell

services:
  - docker

env:
  DOCKER_USERNAME: sineverba
  DOCKER_IMAGE: php74xc

before_install:
  - chmod +x ./deploy/scripts/test.sh
  - chmod +x ./deploy/scripts/deploy.sh

install:
  - docker build --tag $DOCKER_USERNAME/$DOCKER_IMAGE .

script:
  - ./deploy/scripts/test.sh

after_success:
  - |
    if [[ $TRAVIS_TAG != "" ]]; then
      ./deploy/scripts/deploy.sh
    fi